version: '3.8'

services:

  front-end:
    image: ubuntu:20.04
    working_dir: /usr/src/app
    volumes:
      - ./example-frontend:/usr/src/app
    ports:
      - "5000:5000"
    command: bash -c "apt-get update && apt-get install -y curl && \
                      curl -sL https://deb.nodesource.com/setup_16.x | bash && \
                      apt-get install -y nodejs && \
                      node -v && npm -v && \
                      npm install && \
                      npm run build && \
                      npm install -g serve && \
                      serve -s -l 5000 build"
    depends_on:
      - back-end
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/
    # networks:
    #   - my-network

  back-end:
    image: ubuntu:20.04
    working_dir: /usr/src/app
    volumes:
      - ./example-backend:/usr/src/app
    ports:
      - "8080:8080"
    command: bash -c "apt-get update && apt-get install -y ca-certificates gcc g++ && \
                      rm -rf /usr/local/go && tar -C /usr/local -xzf /usr/src/app/go1.16.15.linux-amd64.tar.gz && \
                      export PATH=\"$PATH:/usr/local/go/bin\" && \
                      go version && \
                      go build && \
                      go test ./... && \
                      ./server REQUEST_ORIGIN=https://example.com"
    # networks:
    #   - my-network

# networks:
#   my-network:
#     driver: bridge
